<!-- titles -->
<?php $title = "home" ?>
<?php $mainTitle = "<h2 class='text-center black'>Collants sorcière enfant fluo</h2>" ?>
<?php $previous = "Boutique" ?>

<!-- primary content  -->
<?php ob_start(); ?>
Phasellus et velit diam. Mauris non ante varius, ultricies magna a, feugiat dui. Vivamus tempor dictum nibh quis tempus. Aenean mattis, quam vitae ultrices aliquet, purus ante convallis neque, commodo ultrices leo elit nec eros. Sed vehicula magna sit amet felis tristique, et interdum elit ullamcorper. Ut porttitor lorem purus, ac semper justo faucibus nec. Donec tellus enim, bibendum vel faucibus a, tincidunt sit amet lorem. Nulla ullamcorper turpis eget sodales vulputate. Curabitur dictum urna a lorem viverra, vel faucibus nisl vehicula. Mauris sagittis dui a nisl vestibulum luctus.
Phasellus et velit diam. Mauris non ante varius, ultricies magna a, feugiat dui. Vivamus tempor dictum nibh quis tempus. Aenean mattis, quam vitae ultrices aliquet, purus ante convallis neque, commodo ultrices leo elit nec eros. Sed vehicula magna sit amet felis tristique, et interdum elit ullamcorper. Ut porttitor lorem purus, ac semper justo faucibus nec. Donec tellus enim, bibendum vel faucibus a, tincidunt sit amet lorem. Nulla ullamcorper turpis eget sodales vulputate. Curabitur dictum urna a lorem viverra, vel faucibus nisl vehicula. Mauris sagittis dui a nisl vestibulum luctus.
Phasellus et velit diam. Mauris non ante varius, ultricies magna a, feugiat dui. Vivamus tempor dictum nibh quis tempus. Aenean mattis, quam vitae ultrices aliquet, purus ante convallis neque, commodo ultrices leo elit nec eros. Sed vehicula magna sit amet felis tristique, et interdum elit ullamcorper. Ut porttitor lorem purus, ac semper justo faucibus nec. Donec tellus enim, bibendum vel faucibus a, tincidunt sit amet lorem. Nulla ullamcorper turpis eget sodales vulputate. Curabitur dictum urna a lorem viverra, vel faucibus nisl vehicula. Mauris sagittis dui a nisl vestibulum luctus.
Phasellus et velit diam. Mauris non ante varius, ultricies magna a, feugiat dui. Vivamus tempor dictum nibh quis tempus. Aenean mattis, quam vitae ultrices aliquet, purus ante convallis neque, commodo ultrices leo elit nec eros. Sed vehicula magna sit amet felis tristique, et interdum elit ullamcorper. Ut porttitor lorem purus, ac semper justo faucibus nec. Donec tellus enim, bibendum vel faucibus a, tincidunt sit amet lorem. Nulla ullamcorper turpis eget sodales vulputate. Curabitur dictum urna a lorem viverra, vel faucibus nisl vehicula. Mauris sagittis dui a nisl vestibulum luctus.
Phasellus et velit diam. Mauris non ante varius, ultricies magna a, feugiat dui. Vivamus tempor dictum nibh quis tempus. Aenean mattis, quam vitae ultrices aliquet, purus ante convallis neque, commodo ultrices leo elit nec eros. Sed vehicula magna sit amet felis tristique, et interdum elit ullamcorper. Ut porttitor lorem purus, ac semper justo faucibus nec. Donec tellus enim, bibendum vel faucibus a, tincidunt sit amet lorem. Nulla ullamcorper turpis eget sodales vulputate. Curabitur dictum urna a lorem viverra, vel faucibus nisl vehicula. Mauris sagittis dui a nisl vestibulum luctus.
Phasellus et velit diam. Mauris non ante varius, ultricies magna a, feugiat dui. Vivamus tempor dictum nibh quis tempus. Aenean mattis, quam vitae ultrices aliquet, purus ante convallis neque, commodo ultrices leo elit nec eros. Sed vehicula magna sit amet felis tristique, et interdum elit ullamcorper. Ut porttitor lorem purus, ac semper justo faucibus nec. Donec tellus enim, bibendum vel faucibus a, tincidunt sit amet lorem. Nulla ullamcorper turpis eget sodales vulputate. Curabitur dictum urna a lorem viverra, vel faucibus nisl vehicula. Mauris sagittis dui a nisl vestibulum luctus.
Phasellus et velit diam. Mauris non ante varius, ultricies magna a, feugiat dui. Vivamus tempor dictum nibh quis tempus. Aenean mattis, quam vitae ultrices aliquet, purus ante convallis neque, commodo ultrices leo elit nec eros. Sed vehicula magna sit amet felis tristique, et interdum elit ullamcorper. Ut porttitor lorem purus, ac semper justo faucibus nec. Donec tellus enim, bibendum vel faucibus a, tincidunt sit amet lorem. Nulla ullamcorper turpis eget sodales vulputate. Curabitur dictum urna a lorem viverra, vel faucibus nisl vehicula. Mauris sagittis dui a nisl vestibulum luctus.
<?php $primaryContent = ob_get_clean(); ?>

<!-- secondary content -->
<?php ob_start(); ?>
Phasellus et velit diam. Mauris non ante varius, ultricies magna a, feugiat dui. Vivamus tempor dictum nibh quis tempus. Aenean mattis, quam vitae ultrices aliquet, purus ante convallis neque, commodo ultrices leo elit nec eros. Sed vehicula magna sit amet felis tristique, et interdum elit ullamcorper. Ut porttitor lorem purus, ac semper justo faucibus nec. Donec tellus enim, bibendum vel faucibus a, tincidunt sit amet lorem. Nulla ullamcorper turpis eget sodales vulputate. Curabitur dictum urna a lorem viverra, vel faucibus nisl vehicula. Mauris sagittis dui a nisl vestibulum luctus.
Phasellus et velit diam. Mauris non ante varius, ultricies magna a, feugiat dui. Vivamus tempor dictum nibh quis tempus. Aenean mattis, quam vitae ultrices aliquet, purus ante convallis neque, commodo ultrices leo elit nec eros. Sed vehicula magna sit amet felis tristique, et interdum elit ullamcorper. Ut porttitor lorem purus, ac semper justo faucibus nec. Donec tellus enim, bibendum vel faucibus a, tincidunt sit amet lorem. Nulla ullamcorper turpis eget sodales vulputate. Curabitur dictum urna a lorem viverra, vel faucibus nisl vehicula. Mauris sagittis dui a nisl vestibulum luctus.
Phasellus et velit diam. Mauris non ante varius, ultricies magna a, feugiat dui. Vivamus tempor dictum nibh quis tempus. Aenean mattis, quam vitae ultrices aliquet, purus ante convallis neque, commodo ultrices leo elit nec eros. Sed vehicula magna sit amet felis tristique, et interdum elit ullamcorper. Ut porttitor lorem purus, ac semper justo faucibus nec. Donec tellus enim, bibendum vel faucibus a, tincidunt sit amet lorem. Nulla ullamcorper turpis eget sodales vulputate. Curabitur dictum urna a lorem viverra, vel faucibus nisl vehicula. Mauris sagittis dui a nisl vestibulum luctus.
Phasellus et velit diam. Mauris non ante varius, ultricies magna a, feugiat dui. Vivamus tempor dictum nibh quis tempus. Aenean mattis, quam vitae ultrices aliquet, purus ante convallis neque, commodo ultrices leo elit nec eros. Sed vehicula magna sit amet felis tristique, et interdum elit ullamcorper. Ut porttitor lorem purus, ac semper justo faucibus nec. Donec tellus enim, bibendum vel faucibus a, tincidunt sit amet lorem. Nulla ullamcorper turpis eget sodales vulputate. Curabitur dictum urna a lorem viverra, vel faucibus nisl vehicula. Mauris sagittis dui a nisl vestibulum luctus.
Phasellus et velit diam. Mauris non ante varius, ultricies magna a, feugiat dui. Vivamus tempor dictum nibh quis tempus. Aenean mattis, quam vitae ultrices aliquet, purus ante convallis neque, commodo ultrices leo elit nec eros. Sed vehicula magna sit amet felis tristique, et interdum elit ullamcorper. Ut porttitor lorem purus, ac semper justo faucibus nec. Donec tellus enim, bibendum vel faucibus a, tincidunt sit amet lorem. Nulla ullamcorper turpis eget sodales vulputate. Curabitur dictum urna a lorem viverra, vel faucibus nisl vehicula. Mauris sagittis dui a nisl vestibulum luctus.
Phasellus et velit diam. Mauris non ante varius, ultricies magna a, feugiat dui. Vivamus tempor dictum nibh quis tempus. Aenean mattis, quam vitae ultrices aliquet, purus ante convallis neque, commodo ultrices leo elit nec eros. Sed vehicula magna sit amet felis tristique, et interdum elit ullamcorper. Ut porttitor lorem purus, ac semper justo faucibus nec. Donec tellus enim, bibendum vel faucibus a, tincidunt sit amet lorem. Nulla ullamcorper turpis eget sodales vulputate. Curabitur dictum urna a lorem viverra, vel faucibus nisl vehicula. Mauris sagittis dui a nisl vestibulum luctus.
Phasellus et velit diam. Mauris non ante varius, ultricies magna a, feugiat dui. Vivamus tempor dictum nibh quis tempus. Aenean mattis, quam vitae ultrices aliquet, purus ante convallis neque, commodo ultrices leo elit nec eros. Sed vehicula magna sit amet felis tristique, et interdum elit ullamcorper. Ut porttitor lorem purus, ac semper justo faucibus nec. Donec tellus enim, bibendum vel faucibus a, tincidunt sit amet lorem. Nulla ullamcorper turpis eget sodales vulputate. Curabitur dictum urna a lorem viverra, vel faucibus nisl vehicula. Mauris sagittis dui a nisl vestibulum luctus.
<?php $secondaryContent = ob_get_clean(); ?>

<!-- include -->
<?php require('layout-2.php'); ?>
